FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .

WORKDIR /src/PlcSim
RUN dotnet restore PlcSim.csproj
RUN dotnet publish PlcSim.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

# Needed for health check
RUN apt-get update && apt-get install -y curl

ENTRYPOINT ["dotnet", "PlcSim.dll"]
